spring.application.name=UserMS
server.port=9090
spring.datasource.url=jdbc:mysql://localhost:3306/usersdb?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===================================================================
# 3. إعدادات الـ JWT Token لفك التشفير وحماية الـ Controllers
# ===================================================================
alerthub.jwt.secret=MyAlertHubSuperSecretKeyForJWTTokenSigning2026!
alerthub.jwt.expiration-ms=86400000

# ===================================================================
# 4. روابط الـ OpenFeign للاتصال بالخدمات الأخرى (Local Environment)
# ===================================================================
app.services.security-url=http://localhost:8081
app.services.metrics-url=http://localhost:8082
app.services.action-url=http://localhost:8083
app.services.evaluation-url=http://localhost:8084
